name: hosrem_app
description: Hosrem Application

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc: ^0.21.0
  equatable: ^0.5.1
  shared_preferences: ^0.5.3+4
  path_provider: ^1.3.0
  fluro: ^1.5.1
  sqflite: ^1.1.6+4
  jaguar_orm: ^2.2.6
  jaguar_query_sqflite: ^2.2.10
  connectivity: ^0.4.4
  cached_network_image: ^1.1.1
  dio: ^3.0.3
  pull_to_refresh: ^1.5.6
  logging: ^0.11.3+2
  flutter_facebook_login: ^3.0.0
  retrofit: ^1.0.1
  json_annotation: ^3.0.0
  flutter_alert: ^0.4.0
  easy_localization: ^1.3.1
  loading_overlay: ^0.2.0
  flutter_full_pdf_viewer: ^1.0.6
  bubble_tab_indicator: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.0.1+1
  build_runner: ^1.7.1
  json_serializable: ^3.2.2


flutter:
  uses-material-design: true
  assets:
  - assets/images/logo.png
  - assets/langs/vi-VN.json
  - assets/langs/en-US.json
