name: hosrem_app
description: Hosrem Application

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc: ^0.21.0
  equatable: ^0.5.1
  shared_preferences: ^0.5.3+4
  path_provider: ^1.3.0
  fluro: ^1.5.1
  sqflite: ^1.1.6+4
  jaguar_orm: ^2.2.6
  jaguar_query_sqflite: ^2.2.10
  connectivity: ^0.4.4
  cached_network_image: ^1.1.1
  dio: ^3.0.3
  pull_to_refresh: ^1.5.6
  logging: ^0.11.3+2
  flutter_facebook_login: ^3.0.0
  retrofit: ^1.0.1
  json_annotation: ^3.0.0
  flutter_alert: ^0.4.0
  easy_localization: ^1.3.1
  loading_overlay: ^0.2.0
  flutter_full_pdf_viewer: ^1.0.6
  photo_view: ^0.6.0
  bubble_tab_indicator: ^0.1.4
  flutter_svg: ^0.14.1
  date_format: ^1.0.6
  sticky_headers: ^0.1.8
  corsac_jwt: ^0.1.2
  flutter_cache_manager: ^1.1.1
  page_transition: ^1.1.5
  timeago: ^2.0.20
  firebase_messaging: ^5.1.6
  collection: ^1.14.11
  flutter_money_formatter: ^0.8.3
  flutter_webview_plugin: ^0.3.8
  pretty_qr_code: ^0.0.8
  flutter_html: ^0.11.0
  firebase_crashlytics: ^0.1.0+3
  momo:
    path: ../momo

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.0.1+1
  build_runner: ^1.7.1
  json_serializable: ^3.2.2

flutter:
  uses-material-design: true
  assets:
  - assets/images/logo.png
  - assets/images/home_normal.svg
  - assets/images/home_selected.svg
  - assets/images/event_normal.svg
  - assets/images/event_selected.svg
  - assets/images/notification_normal.svg
  - assets/images/notification_selected.svg
  - assets/images/profile_normal.svg
  - assets/images/profile_selected.svg
  - assets/images/conference_placeholder.png
  - assets/images/registered.svg
  - assets/images/pdf_file_type.svg
  - assets/images/jpg_file_type.svg
  - assets/images/search.svg
  - assets/images/expired.svg
  - assets/images/email.svg
  - assets/images/notice.svg
  - assets/images/location.svg
  - assets/images/calendar.svg
  - assets/images/profile_placeholder.svg
  - assets/images/diamond.svg
  - assets/images/pencil.svg
  - assets/images/megaphone.svg
  - assets/images/gift.svg
  - assets/images/card.svg
  - assets/images/momo.png
  - assets/images/zalo.png
  - assets/images/onepay.png
  - assets/images/card_green.png
  - assets/images/card_purple.png
  - assets/images/atm.png
  - assets/images/mastercard.png
  - assets/images/visa.png
  - assets/images/confirm.svg
  - assets/images/article_placeholder.png
  - assets/images/survey.png
  - assets/images/emote_1_normal.svg
  - assets/images/emote_1_selected.svg
  - assets/images/emote_2_normal.svg
  - assets/images/emote_2_selected.svg
  - assets/images/emote_3_normal.svg
  - assets/images/emote_3_selected.svg
  - assets/images/emote_4_normal.svg
  - assets/images/emote_4_selected.svg
  - assets/images/emote_5_normal.svg
  - assets/images/emote_5_selected.svg
  - assets/langs/vi-VN.json
  - assets/langs/en-US.json

  fonts:
  - family: Muli
    fonts:
    - asset: assets/fonts/Muli.ttf
      style: normal
    - asset: assets/fonts/Muli-Italic.ttf
      style: italic
    - asset: assets/fonts/Muli-Bold.ttf
      weight: 600
