# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Distribute iOS app on Firebase"
  lane :firebase do
    increment_build_number
    gym
    firebase_app_distribution(
      app: "1:415552824898:ios:b09cb4ea482990dbc8afdb",
      ipa_path: "Runner.ipa",
      groups: "qa-group",
      release_notes: "Development release",
      firebase_cli_path: "/Users/anle/Applications/firebase"
    )
  end
end
