# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Distribute android app on Firebase"
    lane :firebase do
      gradle(
        task: "clean"
      )
      gradle(
        task: "assemble",
        build_type: "Release"
      )
      firebase_app_distribution(
        app: "1:415552824898:android:1a26dcb89b03aaf6c8afdb",
        apk_path: "../build/app/outputs/apk/release/app-release.apk",
        groups: "qa-group",
        release_notes: "Dev release",
        firebase_cli_path: "/Users/anle/Applications/firebase"
      )
    end
end
